apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sparkyfitness.fullname" . }}-server-backup
  labels:
    {{- include "sparkyfitness.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  accessModes:
    - {{ .Values.server.persistence.backup.accessMode }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.backup.size }}
  {{- with .Values.global.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
