{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.appdb.enabled }}
apiVersion: external-secrets.io/{{ .Values.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "sparkyfitness.fullname" . }}-appdb
  labels:
    {{- include "sparkyfitness.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    {{- if .Values.externalSecrets.appdb.clusterSecretStore }}
    name: {{ .Values.externalSecrets.appdb.clusterSecretStore }}
    kind: ClusterSecretStore
    {{- else }}
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: SecretStore
    {{- end }}
  target:
    name: {{ include "sparkyfitness.appDbSecretName" . }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.appdb.keys }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ $.Values.externalSecrets.appdb.remoteKey }}
        property: {{ .property }}
    {{- end }}
{{- end }}
