{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.oidc.enabled }}
apiVersion: external-secrets.io/{{ .Values.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "sparkyfitness.fullname" . }}-oidc
  labels:
    {{- include "sparkyfitness.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ include "sparkyfitness.oidcSecretName" . }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.oidc.keys }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ $.Values.externalSecrets.oidc.remoteKey }}
        property: {{ .property }}
    {{- end }}
{{- end }}
