{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.postgres.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "sparkyfitness.fullname" . }}-postgres
  labels:
    {{- include "sparkyfitness.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    {{- if .Values.externalSecrets.postgres.clusterSecretStore }}
    name: {{ .Values.externalSecrets.postgres.clusterSecretStore }}
    kind: ClusterSecretStore
    {{- else }}
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: SecretStore
    {{- end }}
  target:
    name: {{ include "sparkyfitness.databaseSecretName" . }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.postgres.keys }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ $.Values.externalSecrets.postgres.remoteKey }}
        property: {{ .property }}
    {{- end }}
{{- end }}
