{{- if include "sparkyfitness.createOidcSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sparkyfitness.oidcSecretName" . }}
  labels:
    {{- include "sparkyfitness.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.oidc.secrets.clientId }}
  client_id: {{ .Values.config.oidc.secrets.clientId | b64enc }}
  {{- end }}
  {{- if .Values.config.oidc.secrets.clientSecret }}
  client_secret: {{ .Values.config.oidc.secrets.clientSecret | b64enc }}
  {{- end }}
{{- end }}
