{{- if include "sparkyfitness.createSmtpSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sparkyfitness.smtpSecretName" . }}
  labels:
    {{- include "sparkyfitness.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.email.secrets.username }}
  username: {{ .Values.config.email.secrets.username | b64enc }}
  {{- end }}
  {{- if .Values.config.email.secrets.password }}
  password: {{ .Values.config.email.secrets.password | b64enc }}
  {{- end }}
{{- end }}
