{{- if and .Values.config.garmin.enabled (and .Values.global.serviceAccount.create .Values.garmin.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sparkyfitness.fullname" . }}-garmin
  labels:
    {{- include "sparkyfitness.labels" . | nindent 4 }}
    app.kubernetes.io/component: garmin
  {{- with .Values.garmin.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.garmin.serviceAccount.automountServiceAccountToken }}
{{- end }}
