{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "sparkyfitness.fullname" . }}
  labels:
    {{- include "sparkyfitness.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.parentRef.name }}
      namespace: {{ .Values.httpRoute.parentRef.namespace }}
      {{- with .Values.httpRoute.parentRef.sectionName }}
      sectionName: {{ . }}
      {{- end }}
  hostnames:
    - {{ .Values.httpRoute.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "sparkyfitness.fullname" . }}-frontend
          port: {{ .Values.frontend.port }}
{{- end }}
